<div class="container lookup-wallet">
    <div class="row justify-content-center">
        <div class="col-12 col-md-10 col-lg-8 pb-5">

            <h3>WL Checker</h3>
            <p class="special-font">
                <?=number_format($totalWallets); ?> wallets on the WL
            </p>

            <div id="check" class="hide">
                <img width="50" alt="Eo circle green checkmark" src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Eo_circle_green_checkmark.svg/512px-Eo_circle_green_checkmark.svg.png?20200417132424">
            </div>
            <div id="success-response">
                <form id="lookup-wallet" method="post" action="" class="row g-3 align-items-center">
                    <div class="col-12">
                        <input
                            type="text"
                            name="wallet"
                            id="wallet"
                            class="form-control"
                            placeholder="0xabc..."
                            value=""
                        />
                    </div>
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary w-100">Look-Up</button>
                    </div>
                </form>
            </div>
            <div id="failure-response" class="hide row gx-3 align-items-center mt-4 py-2 bg-danger rounded"></div>

        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row justify-content-center my-5">
        <?php foreach ($images as $image): ?>
            <div class="col col-6 col-lg-3">
                <img class="img-fluid" src="<?=env('APP_ORIGIN_URL'); ?>/assets/images/example_images/<?=$image; ?>" />
            </div>
        <?php endforeach; ?>
    </div>
</div>

<div class="container">
    <div class="row justify-content-center">
        <div class="col col-12 col-md-10 col-lg-10">
            <p class="d-block mb- p-large special-font">
                Holders from the following collections are on the whitelist (alphabetical order)
            </p>
            <?php foreach ($whitelistCollections as $whitelistCollection): ?>
                <div class="badge bg-black">
                    <?=$whitelistCollection; ?>
                </div>
            <?php endforeach; ?>
        </div>
<!--        <div class="col col-6">-->
<!--            Find Your No-Based-->
<!--        </div>-->
    </div>
</div>

<div class="container profile">
    <div class="row justify-content-center mt-5">
        <div class="col col-12 col-md-10 col-lg-8 mt-5 about">
            <h2>About the artist</h2>
            <p class="regular-text">
                I'm a professional web developer with a passion for coding and digital art.
                On Base, I will create free mints on <a target="_blank" href="https://highlight.xyz/user/@0xf33B9684B37542Cfe043e4cA9F1B3AbecE177976">highlight.xyz</a> and one paid mint on <a target="_blank" href="https://opensea.io/collection/nobaseism/">OpenSea</a> (with an 80%+ free WL), simply because I love creating and enjoy seeing my art in collectors' wallets.
                I won't stop creating; I will continue adding new free collections on Highlight at irregular intervals. No hype, just fun art. If you like my work, you can support me by minting No-Based or one of the free mints on highlight.xyz.
            </p>
            <p>
                See ya,<br />
                Mike from The Netherlands
            </p>
        </div>
    </div>

    <hr class="m-5 pb-2" />

    <div class="row justify-content-center mt-5 about mb-4 pb-5">
        <p class="regular-text">
            Here are my other collections available for free minting on Highlight.
            There's a small marketplace fee of 0.0008 ETH, with 50% of that going directly to my wallet.
            If you'd like to support my work, feel free to mint and help put "Mike" on the trending list! :)
        </p>
        <h2>
            <a target="_blank" href="https://highlight.xyz/mint/base:0x4C58a4513c2276567Fe1c11BE79cFA11EbFaFc08">
                BasedDickbutts
            </a>
        </h2>
        <div class="col col-6 col-lg-3">
            <a target="_blank" href="https://highlight.xyz/mint/base:0x4C58a4513c2276567Fe1c11BE79cFA11EbFaFc08">
                <img class="img-fluid" src="<?=env('APP_ORIGIN_URL'); ?>/assets/images/baseddickbutts/1.png" />
            </a>
        </div>
        <div class="col col-6 col-lg-3">
            <a target="_blank" href="https://highlight.xyz/mint/base:0x4C58a4513c2276567Fe1c11BE79cFA11EbFaFc08">
                <img class="img-fluid" src="<?=env('APP_ORIGIN_URL'); ?>/assets/images/baseddickbutts/2.png" />
            </a>
        </div>
        <div class="col col-6 col-lg-3">
            <a target="_blank" href="https://highlight.xyz/mint/base:0x4C58a4513c2276567Fe1c11BE79cFA11EbFaFc08">
                <img class="img-fluid" src="<?=env('APP_ORIGIN_URL'); ?>/assets/images/baseddickbutts/3.png" />
            </a>
        </div>
    </div>
</div>
