<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mike from No-Based">

    <title><?=$htmlTitle; ?></title>

    <link href="<?=env('URL'); ?>/assets/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?=env('URL'); ?>/assets/css/main.css?t=<?=date('dmYHi'); ?>" rel="stylesheet">
</head>

<body>
    <main>
        <?=$content; ?>
    </main>

    <div class="container-fluid container-socials">
        <div class="row justify-content-center">
            <div class="col">
                <p>IT’S TIME TO RE:SET HOW WE FEEL ABOUT ART</p>
                <br />
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col col-12 col-lg-6 col-sm-12 text-center">
                <a href="https://x.com/re_generates" target="_blank" class="btn">
                    OFFICIAL RE:GEN ACCOUNT ON X
                </a>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col col-12 col-lg-6 col-sm-12 text-center">
                <a href="https://discord.com/invite/ANyfeM4txt" target="_blank" class="btn">
                    RE:GENS ON DISCOARD
                </a>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col col-12 col-lg-6 col-sm-12 text-center">
                <a href="https://base.mintify.xyz/base/0x56dfe6ae26bf3043dc8fdf33bf739b4ff4b3bc4a" target="_blank" class="btn">
                    RE:GENS ON MINTIFY
                </a>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col col-12 col-lg-6 col-sm-12 text-center">
                <a href="https://opensea.io/collection/re-gens" target="_blank" class="btn">
                    RE:GENS ON OPENSEA
                </a>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col col-12 col-lg-6 col-sm-12 text-center">
                <a href="https://opensea.io/collection/re-mixs" target="_blank" class="btn">
                    RE:MIX BY MECHSICKO & FRIENDS
                </a>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col col-12 col-lg-6 col-sm-12 text-center">
                <a href="https://x.com/mechsicko_eth" target="_blank" class="btn">
                    MECHSICKO'S ONLY X ACCOUNT
                </a>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col col-12 col-lg-6 col-sm-12 text-center">
                <a href="https://open.spotify.com/artist/4bDrkKKgSWLRkOMdjD3jcu?si=xZ91ZUlKS-izif_3Hzv3Wg" target="_blank" class="btn">
                    MECHSICKO ON SPOTIFY
                </a>
            </div>
        </div>
    </div>

    <footer class="p-5">
        <p>
            re:generates is a 6,666 collection created and minted on the Base blockchain.
            The collection is created by the artist <a href="https://opensea.io/mechsicko" target="_blank">mechsicko</a>
        </p>
    </footer>

    <div id="mike">
        Website built by Mike, that guy from No-Based.
    </div>

    <script type="text/javascript" src="<?=env('URL'); ?>/assets/js/main.js"></script>
</body>

</html>
