<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mike from No-Based">

    <title><?=$htmlTitle; ?></title>

    <link href="<?=env('URL'); ?>/assets/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?=env('URL'); ?>/assets/css/main.css?t=<?=date('dmYHi'); ?>" rel="stylesheet">
</head>

<body>

    <!-- Sticky Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
        <div class="container-fluid">
            <!-- Navbar Brand/Title -->
            <a class="navbar-brand" href="<?=env('URL'); ?>">RE:GENS</a>

            <!-- Toggle Button for Mobile View -->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Navbar Links and Search -->
            <div class="collapse navbar-collapse" id="navbarContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <!-- Dropdown Menu (Left) -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Socials / Community
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>
                                <a href="https://x.com/re_generates" target="_blank" class="dropdown-item">OFFICIAL RE:GEN ACCOUNT ON X</a>
                            </li>
                            <li>
                                <a href="https://discord.com/invite/ANyfeM4txt" target="_blank" class="dropdown-item">RE:GENS ON DISCORD</a>
                            </li>
                            <li>
                                <a href="https://base.mintify.xyz/base/0x56dfe6ae26bf3043dc8fdf33bf739b4ff4b3bc4a" target="_blank" class="dropdown-item">RE:GENS ON MINTIFY</a>
                            </li>
                            <li>
                                <a href="https://opensea.io/collection/re-gens" target="_blank" class="dropdown-item">RE:GENS ON OPENSEA</a>
                            </li>
                            <li>
                                <a href="https://opensea.io/collection/re-mixs" target="_blank" class="dropdown-item">RE:MIX BY MECHSICKO & FRIENDS</a>
                            </li>
                            <li>
                                <a href="https://x.com/mechsicko_eth" target="_blank" class="dropdown-item">MECHSICKO'S ONLY X ACCOUNT</a>
                            </li>
                            <li>
                                <a href="https://open.spotify.com/artist/4bDrkKKgSWLRkOMdjD3jcu?si=xZ91ZUlKS-izif_3Hzv3Wg" target="_blank" class="dropdown-item">MECHSICKO ON SPOTIFY</a>
                            </li>
                            <li>
                                <a href="https://gm-tool.netlify.app/community.html?community=regenerates" target="_blank" class="dropdown-item">RE:M/N TOOL</a>
                            </li>
                            <li>
                                <a href="https://image-grid-tool.netlify.app/" target="_blank" class="dropdown-item">GRID TOOL</a>
                            </li>
                            <li>
                                <a href="https://regen-banner-tool.netlify.app/" target="_blank" class="dropdown-item">BANNER TOOL</a>
                            </li>
                            <li>
                                <a href="https://regen-wallpaper-tool.netlify.app/" target="_blank" class="dropdown-item">PHONE WALLPAPER TOOL</a>
                            </li>
                        </ul>

                    </li>
                </ul>

                <!-- Search Form (Right) -->
                <form id="lookup" method="post" action="<?=env('url'); ?>/lookup" class="d-flex">
                    <input class="form-control me-2" name="regensid" id="regensid" type="text" placeholder="123..." aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>

    <main>
        <?=$content; ?>
    </main>


    <footer class="p-5">
        <p>
            re:generates is a 6,666 collection created and minted on the Base blockchain.
            The collection is created by the artist <a href="https://opensea.io/mechsicko" target="_blank">mechsicko</a>
        </p>
    </footer>

    <div id="mike">
        Website built by Mike, that guy from No-Based.
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>

    <script type="text/javascript" src="<?=env('URL'); ?>/assets/js/main.js"></script>
</body>

</html>
