<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="HasMints.com">

    <title><?=$htmlTitle; ?></title>

    <link href="<?=env('URL'); ?>/assets/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?=env('URL'); ?>/assets/css/main.css?t=<?=date('dmYHi'); ?>" rel="stylesheet">
</head>

<body>
    <main>
        <div class="container-fluid mt-4">
            <div class="row justify-content-center">
                <h1>
                    <a href="<?=env('APP_ORIGIN_URL'); ?>">Weeping Plebs</a>
                </h1>
            </div>
        </div>

        <?=$content; ?>
    </main>

    <footer class="py-4">
        <p class="text-center">Website built by <a target="_blank" href="https://hasmints.com/">HasMints</a>.</p>
    </footer>

    <script type="text/javascript" src="<?=env('URL'); ?>/assets/js/main.js"></script>
</body>

</html>
