<div class="container-fluid mt-4">
    <div class="row justify-content-center">
        <div class="col col-12">
            <h1><a href="<?=env('APP_ORIGIN_URL'); ?>">re:filter</a></h1>
        </div>
    </div>
</div>


<div class="container-fluid mb-2 px-5">
    <div class="row justify-content-center text-center">
        <p>
            <?=$totalFilteredNFTs; ?> re:gen<?=$totalFilteredNFTs > 1 ? 's' : ''; ?> found<?php if ($totalFilteredNFTs > env('FILTER_LIMIT')): ?>, limited to random <?=env('FILTER_LIMIT'); ?><?php endif; ?>
        </p>
        <p>
            <?php foreach (\App\Service\Filter::parse($currentFilter) as $trait => $property): ?>
                <a class="btn" href="<?=env('APP_ORIGIN_URL'); ?>/filter/<?=undo_spaces(\App\Service\Filter::queryRemoveTrait($currentFilter, $trait)); ?>">
                    <?=$property; ?>
                </a>
            <?php endforeach; ?>
        </p>
    </div>
    <div class="row justify-content-center">
        <?php foreach ($filteredNFTs as $NFT): ?>
            <div class="col col-12 col-sm-6 col-md-4 col-lg-3 col-xl-3 col-xxl-3 mt-4">
                <?php require ROOT . "/templates/views/website/partials/nft-card.phtml"; ?>
            </div>
        <?php endforeach; ?>
    </div>
</div>
