<div class="container mt-4 mb-2">
    <div class="row justify-content-center text-center">
        <h1>Weeping Filter</h1>
        <?php if ($totalFilteredNFTs > env('FILTER_LIMIT')): ?>
            <h2><?=$totalFilteredNFTs; ?> Weeping Plebs found, limited to <?=env('FILTER_LIMIT'); ?> random Weeping Plebs</h2>
        <?php else: ?>
            <h2><?=$totalFilteredNFTs; ?> Weeping Plebs found</h2>
        <?php endif; ?>
        <p>
            <?php foreach (\App\Service\Filter::parse($currentFilter) as $trait => $property): ?>
                <?=revert_snake_case($trait); ?>: <?=revert_snake_case($property); ?><br />
            <?php endforeach; ?>
        </p>
    </div>
    <div class="row justify-content-center">
        <?php foreach ($filteredNFTs as $NFT): ?>
            <div class="col col-12 col-sm-3 mt-4">
                <?php require ROOT . "/templates/views/website/partials/nft-card.phtml"; ?>
            </div>
        <?php endforeach; ?>
    </div>
</div>
