<?php
/**
 * @var $NFT \App\Model\NFT
 */
?>
<div class="container mt-4 mb-2">
    <div class="row justify-content-center">
        <div class="col col-12 col-sm-5 mt-4">
            <img class="img-fluid" src="<?=$NFT->getImage(); ?>" />
        </div>
        <div class="col col-12 col-sm-5 mt-4">
            <h1>
                <?=$NFT->getName(); ?>
            </h1>
            <?php foreach ($NFT->getAttributes() as $trait => $property): ?>
                <?=$trait; ?>:
                <a href="/filter/;<?=snake_case($trait); ?>=<?=snake_case($property); ?>">
                    <?=$property; ?>
                </a>
                <br />
            <?php endforeach; ?>
        </div>
    </div>
</div>
