<div class="container mt-5 mb-1">
    <div class="row">
        <div class="col">
            <h1 class="xxl">PigPunks</h1>
            <h2>10,000 pigs with an attitude</h2>
        </div>
    </div>
</div>

<div class="container mt-5 mb-1">
    <div class="row justify-content-center">
        <div class="col col-12">
            <h3>Dec 15, 2024, @ 10:00 AM AST (NY time)</h3>
            <br />
        </div>
        <div class="col col-10 col-sm-12">
            <div class="table-container">
                <div class="table-responsive">
                    <table class="table table-borderless">
                        <tr>
                            <td style="min-width: 110px">1st phase</td>
                            <td style="min-width: 90px">1 hour</td>
                            <td style="min-width: 140px">Free WL Mint</td>
                            <td style="min-width: 120px">-</td>
                            <td style="min-width: 100px">Max. 1</td>
                            <td style="min-width: 220px">For No-Based holders ONLY</td>
                        </tr>
                        <tr>
                            <td>2nd phase<sup>*</sup></td>
                            <td>3 hours</td>
                            <td>Paid WL Mint</td>
                            <td>ETH 0.002</td>
                            <td>Max. 100</td>
                            <td>For anyone based (form + list dropping soon)</td>
                        </tr>
                        <tr>
                            <td>3rd phase</td>
                            <td>Open</td>
                            <td>Paid Public Mint</td>
                            <td>ETH 0.003</td>
                            <td>Unlimited</td>
                            <td>Open phase where bots come thru</td>
                        </tr>
                    </table>
                </div>
            </div>
            <br />
            <p>
                * We tryna avoid that bots eat our mints w/ the paid WL phase.
            </p>
        </div>
    </div>
</div>

<div class="container-fluid mt-5">
    <div class="row row-pigs justify-content-center my-5">
        <?php foreach ($images as $image): ?>
            <div class="col col-6 col-lg-3">
                <div class="card">
                    <div class="card-body">
                        <img class="img-fluid" src="<?=env('APP_ORIGIN_URL'); ?>/assets/images/pigs/<?=$image; ?>.jpg" />
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>


<div class="container about">
    <div class="row justify-content-center">
        <div class="col-12">
            <h3>
                Created by Mike and Merel from <a href="https://nobased.com" target="_blank">No-Based</a>
            </h3>
        </div>
    </div>
</div>

