<h1 class="subpage">
    <img width="100" class="logo" src="./assets/images/logo.png" />
    <span class="text">
        Lookup
    </span>
</h1>

<div class="container lookup-wallet mt-5">

    <div class="card">
        <div class="card-body">
            <div class="row justify-content-center">
                <div class="col-12 col-md-10 col-lg-6 py-1">
                    <form id="lookup-nobased" method="post" action="" class="row g-3 align-items-center">
                        <div class="col-12">
                            <input
                                type="text"
                                name="nobasedid"
                                id="nobasedid"
                                class="form-control"
                                placeholder="15..."
                                value=""
                            />
                        </div>
                        <div class="col-12">
                            <button type="submit" class="btn btn-primary w-100">No-Based Check</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="card mt-3">
        <div class="card-body">
            <div id="success-response-nobased" class="row justify-content-center">
                Images will appear here after the look-up.
            </div>
        </div>
    </div>


</div>
