<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Luc">

    <title><?=$htmlTitle; ?></title>

    <link href="<?=env('URL'); ?>/assets/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?=env('URL'); ?>/assets/css/main.css?t=<?=date('dmYHi'); ?>" rel="stylesheet">

    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
</head>

<body data-url="<?=env('URL'); ?>">

    <main>
        <?=$content; ?>
    </main>

    <script type="text/javascript" src="<?=env('URL'); ?>/assets/js/bootstrap.bundle.js"></script>
    <script type="text/javascript" src="<?=env('URL'); ?>/assets/js/main.js"></script>
</body>

</html>
