<div class="container mt-3">
    <div class="row">
        <div class="col">
            <div class="progress">
                <div class="progress-bar" role="progressbar" style="width: <?=$percentageDone; ?>%" aria-valuenow="<?=$percentageDone; ?>" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
        </div>
    </div>
</div>
<div class="container mt-3">
    <div class="row">
        <div class="col">
            <div class="progress">
                <div class="progress-bar" role="progressbar" style="width: <?=$percentageYearDone; ?>%" aria-valuenow="<?=$percentageYearDone; ?>" aria-valuemin="0" aria-valuemax="100"></div>
                <div class="progress-bar progress-bar-missing" role="progressbar" style="width: <?=$percentageYearMissing; ?>%" aria-valuenow="<?=$percentageYearMissing; ?>" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            <?php if ($missingPointsThisYear > 0): ?>
                <small>
                    <?=$missingPointsThisYear; ?> missing points for 2025
                </small>
            <?php endif; ?>
        </div>
    </div>
</div>

<div class="container mt-3">
    <div class="row">
        <div class="col">
            <div class="table-responsive">
                <table class="table">
                    <?php foreach($exercisesGrouped as $type => $exerciseCollection): ?>
                        <tr class="exercises-group">
                            <td colspan="2" class="text-start">
                                <strong>
                                    <?=$type; ?>
                                </strong>
                            </td>
                        </tr>
                        <?php foreach ($exerciseCollection as $exerciseLabel => $exerciseData): ?>
                        <tr class="exercises-done">
                            <td style="width: 60px" class="text-start">
                                <?=$exerciseData['count']; ?><?=$exerciseData['enum']->type(); ?>
                            </td>
                            <td><?=$exerciseLabel; ?></td>
                        </tr>
                        <?php endforeach; ?>
                    <?php endforeach; ?>
                    <tr>
                        <td colspan="2"></td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>