
<div class="container mt-3 bg-white pt-4">

    <div class="row">
        <div class="col px-4 mb-3">
            <img class="mr-3" src="./assets/images/loading.gif" />
        </div>
    </div>

    <div class="row">
        <div class="col px-4 mb-3">
            <div class="progress">
                <div class="progress-bar" role="progressbar" style="width: <?=$percentageDone; ?>%" aria-valuenow="<?=$percentageDone; ?>" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            <?php if ($pointsDoneToday < $pointsDailyGoal): ?>
                <small>
                    <?=$pointsDoneToday; ?> / <?=$pointsDailyGoal; ?>
                </small>
            <?php else: ?>
                <small>
                    <?=$pointsDailyGoal; ?> + <?=($pointsDoneToday - $pointsDailyGoal); ?> = <strong><?=$pointsDoneToday; ?></strong>
                </small>
            <?php endif; ?>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <div class="table-responsive">
                <table class="table">
                    <?php foreach($exercisesGrouped as $type => $exerciseCollection): ?>
                        <tr class="exercises-group">
                            <td colspan="2" class="text-start">
                                <strong>
                                    <?=$type; ?>
                                </strong>
                            </td>
                        </tr>
                        <?php foreach ($exerciseCollection as $exerciseLabel => $exerciseData): ?>
                        <tr class="exercises-done">
                            <td style="width: 60px" class="text-start">
                                <?=$exerciseData['count']; ?><?=$exerciseData['enum']->type(); ?>
                            </td>
                            <td><?=$exerciseLabel; ?></td>
                        </tr>
                        <?php endforeach; ?>
                    <?php endforeach; ?>
                    <tr>
                        <td colspan="2"></td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>