<div id="tasks"></div>

<div class="container mb-1">
    <div class="row">
        <div class="col">
            <?php foreach ($examples as $project => $projectExamples): ?>
                <div data-example="<?=$project; ?>" class="mb-2 examples-project" style="display: none;">
                    <div class="btn-toolbar" role="toolbar">
                        <div class="btn-group" role="group" aria-label="Action buttons">
                            <button class="btn btn-lg btn-primary disabled" disabled>
                                <?=\App\ProjectsEnum::from($project)->abbr(); ?>
                            </button>
                            <?php foreach ($projectExamples as $key => $example): ?>
                                <button data-text="<?=$example; ?>" id="example" data-key="example-<?=$key; ?>" class="btn btn-lg btn-primary">
                                    <?=$key; ?>
                                </button>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>
