<div class="container mb-5">
    <div class="row">
        <div class="col col-12 col-lg-6 mt-4">
            <div id="sport-type-actions">
                <table>
                    <?php foreach ($sportTypes as $subject => $exercises): ?>
                        <tr>
                            <td style="width: 120px; vertical-align: top; padding-top: 20px;">
                                <?=$subject; ?>
                            </td>
                            <td style="vertical-align: top; padding-top: 15px;">
                                <?php foreach ($exercises as $exercise): ?>
                                    <div class="btn-group mt-1" style="margin-left: 5px;" role="group" aria-label="Sport Type Actions">
                                        <button
                                            data-sport-type="<?=$exercise['enum']->value; ?>"
                                            class="btn btn-primary async-sport-type-action-btn no-wrap"
                                        >
                                            <?=$exercise['clean']; ?>
                                        </button>
                                        <button
                                            data-sport-type="<?=$exercise['enum']->value; ?>"
                                            data-multiple="12"
                                            class="btn btn-primary async-sport-type-action-btn no-wrap"
                                        >
                                            x12
                                        </button>
                                    </div>
                                <?php endforeach; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </div>
        </div>
        <div class="col col-12 col-lg-6">
            <div id="sports"></div>
        </div>
    </div>
</div>

<br />
<br />

<div class="container">
    <div class="row">
        <div class="col pt-3">

            <div class="progress">
                <div class="progress-bar" role="progressbar" style="width: <?=$percentageYearDone; ?>%" aria-valuenow="<?=$percentageYearDone; ?>" aria-valuemin="0" aria-valuemax="100"></div>
                <div class="progress-bar progress-bar-missing" role="progressbar" style="width: <?=$percentageYearMissing; ?>%" aria-valuenow="<?=$percentageYearMissing; ?>" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            <?php if ($missingPointsThisYear > 0): ?>
                <small>
                    missing <?=$missingPointsThisYear; ?> points for 2025
                </small>
            <?php else: ?>
                <small>
                    you are ahead of track!
                </small>
            <?php endif; ?>

            <br />
            <br />

            <div id="sports-year">
                <div class="table-responsive">
                    <table class="table table-year-progress">
                        <?php $index = 1; ?>
                        <?php foreach($yearExercisesGrouped as $type => $exerciseCollection): ?>
                            <tr class="exercises-group">
                                <td colspan="2" class="text-start">
                                    <strong>
                                        <?=$type; ?>
                                    </strong>
                                    <?php if ($index === 1): ?>
                                        <div class="float-end pd-3">
                                            2025&nbsp;&nbsp;&nbsp;&nbsp;
                                        </div>
                                    <?php endif; ?>
                                </td>
                            </tr>
                            <?php foreach ($exerciseCollection as $exerciseLabel => $exerciseData): ?>
                                <tr class="exercises-done">
                                    <td style="width: 60px" class="text-start">
                                        <?=$exerciseData['count']; ?><?=$exerciseData['enum']->type(); ?>
                                    </td>
                                    <td><?=$exerciseLabel; ?></td>
                                </tr>
                            <?php endforeach; ?>
                            <?php $index++; ?>
                        <?php endforeach; ?>
                        <tr>
                            <td colspan="2"></td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

