<div id="sport-type-actions" class="container mt-3">
    <?php foreach ($sportTypes as $subject => $exercises): ?>
        <div class="btn-group mb-1" role="group" aria-label="Sport Type Actions">
            <button class="btn btn-secondary" disabled>
                <?=$subject; ?>
            </button>
            <?php foreach ($exercises as $exercise): ?>
                <button
                    data-sport-type="<?=$exercise['enum']->value; ?>"
                    class="btn btn-primary async-sport-type-action-btn"
                >
                    <?=$exercise['clean']; ?>
                </button>
            <?php endforeach; ?>
        </div>
    <?php endforeach; ?>
</div>


<div id="sports"></div>
