<?php
/**
 * @var $NFT \App\Model\NFT
 */
?>
<div class="card">
    <div class="card-header text-center">
        #<?=$NFT->id; ?>
    </div>
    <div class="card-body p-0">
        <a href="<?=env('APP_ORIGIN_URL'); ?>/weepingpleb/<?=$NFT->id; ?>">
            <img class="img-fluid" src="<?=$NFT->getImage(); ?>" />
        </a>
    </div>
    <div class="card-footer">
        <?php foreach ($NFT->getAttributes() as $trait => $property): ?>
            <?php if ($currentFilter): ?>
                <?php if (\App\Service\Filter::queryHasFilter($currentFilter, snake_case($trait))): ?>
                    <a class="badge bg-success" href="<?=env('APP_ORIGIN_URL') . '/filter/'; ?><?=\App\Service\Filter::queryRemoveTrait($currentFilter, snake_case($trait)); ?>">
                        <?=$property; ?>
                    </a>
                <?php else: ?>
                    <a class="badge bg-secondary" href="<?=$currentFilter; ?>;<?=snake_case($trait); ?>=<?=snake_case($property); ?>">
                        <?=$property; ?>
                    </a>
                <?php endif; ?>
            <?php else: ?>
                <a class="badge bg-secondary" href="/filter/<?=snake_case($trait); ?>=<?=snake_case($property); ?>">
                    <?=$property; ?>
                </a>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
</div>
