<div class="container mt-4 mb-2">
    <div class="row justify-content-center">

        <div class="col col-12 col-lg-6 mb-5">
            <img width="100%" class="logo" src="assets/images/logo.png" />
        </div>

        <div class="col col-12 col-lg-6">
            <div class="card">
                <div class="card-body">
                    <h2 class="px-4">
                        <em>
                            "Laser eyes aren't just a meme—they're the symbol of a global crypto revolution."
                        </em>
                    </h2>

                    <div class="input-group mt-4 mb-2">
                        <input type="text" class="form-control" id="contractAddress" value="iKTRRmF3WSd4HEbHfyiRcA2e4vdbtEDkjmCLs3Hpump" disabled>
                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary" type="button" id="copyButton">
                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-clipboard" viewBox="0 0 16 16">
                                    <path d="M10 1.5v1a.5.5 0 0 1-.5.5H6.5a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 .5.5zM4.5 1a1.5 1.5 0 0 0-1.415 1H2.5A1.5 1.5 0 0 0 1 3.5v10A1.5 1.5 0 0 0 2.5 15h11A1.5 1.5 0 0 0 15 13.5v-10A1.5 1.5 0 0 0 13.5 2h-1.085A1.5 1.5 0 0 0 10.5 1h-5zm0 2a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1A.5.5 0 0 1 3 4.5v-1A.5.5 0 0 1 3.5 3h1zm7 0a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1A.5.5 0 0 1 10 4.5v-1a.5.5 0 0 1 .5-.5h1zM2.5 5h11a.5.5 0 0 1 .5.5v8a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-8a.5.5 0 0 1 .5-.5zm.5 1v7h10v-7H3z"/>
                                </svg>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card mt-4">
                <div class="card-body card-links">
                    <h3>$LASER HOW TO</h3>
                    <h4>Step 1:</h4>
                    <a class="btn btn-primary mb-3" href="https://phantom.app/" target="_blank">
                        Download the Phantom app
                    </a>
                    <h4>Step 2:</h4>
                    <a class="btn btn-primary" href="https://jup.ag/swap/SOL-iKTRRmF3WSd4HEbHfyiRcA2e4vdbtEDkjmCLs3Hpump" target="_blank">
                        Swap on Jupiter
                    </a>
                </div>
            </div>

            <div class="card mt-4">
                <div class="card-body card-links">
                    <a href="https://dexscreener.com/solana/iKTRRmF3WSd4HEbHfyiRcA2e4vdbtEDkjmCLs3Hpump" target="_blank">
                        <img class="dexscreener" src="assets/images/dexscreener.png" alt="DEXScreener Icon" />
                    </a>
                    <a href="https://x.com/LASER_CTO_SOL" target="_blank">
                        <img class="x" src="assets/images/x.png" alt="Twitter (X) Icon" />
                    </a>
                    <a href="https://t.me/lasercto" target="_blank">
                        <img class="telegram" src="assets/images/telegram.png" alt="Telegram Icon" />
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container mt-4 mb-2">
    <div class="row justify-content-center row-memes">
        <div class="col-memes col col-12">
            <div class="card">
                <div class="card-body">
                    <h3>Memes Library</h3>
                    <p>
                        <a class="btn btn-primary" href="https://memed.io/laser-eyes-meme-maker" target="_blank">
                            Make your Laser Eyes meme at memed.io
                        </a>
                    </p>
                    <p>
                        Go to the meme maker on memed.io and add it to the library (share it on Telegram and X)
                    </p>
                </div>
            </div>
        </div>

        <?php foreach ($memes as $meme): ?>
            <div class="col col-12 col-lg-3 py-1 col-meme">
                <div class="card p-0">
                    <div class="card-body p-1">
                        <img class="img-fluid" src="./assets/images/memes/<?=$meme; ?>" alt="Meme Image" />
                    </div>
                </div>
            </div>
        <?php endforeach; ?>

        <p class="mt-3">
            <a class="btn btn-lg btn-primary m-0 p-3" href="<?=env('APP_ORIGIN_URL'); ?>">
                Refresh the page to see another selection
            </a>
        </p>
    </div>
</div>

<div class="container-fluid container-disclaimer py-5 mt-4">
    <div class="row justify-content-center">
        <div class="col col-12 col-lg-6">
            <p class="m-0 p-0">
                <strong>Disclaimer:</strong>
                $LASER EYES is a memecoin built on the Solana blockchain and is intended purely for entertainment purposes. This token has no inherent value and should not be considered a financial investment. The value of $LASER EYES may be highly volatile and is driven purely by market speculation. Engaging with $LASER EYES is at your own risk, and you should only participate if you fully understand the risks involved. This is not financial advice. Always conduct your own research before making any decisions related to cryptocurrency.
            </p>
        </div>
    </div>
</div>
